branch-defaults:
  master:
    environment: Newffleserver-env
    group_suffix: null
global:
  application_name: newffle-server
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: studioaries
  repository: origin
  sc: git
  workspace_type: Application
